# Generated by Django 5.1 on 2024-08-23 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LCHIS', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Child',
            new_name='ChildModel',
        ),
        migrations.RenameModel(
            old_name='Guardian',
            new_name='GuardianModel',
        ),
    ]
