# Generated by Django 5.1 on 2024-08-23 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LCHIS', '0002_rename_child_childmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childmodel',
            name='months_old',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='childmodel',
            name='years_old',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='GuardianModel',
        ),
    ]
