# Generated by Django 5.1 on 2024-08-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LCHIS', '0003_alter_childmodel_months_old_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardianModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200, null=True)),
                ('password', models.CharField(max_length=200, null=True)),
                ('children', models.ManyToManyField(to='LCHIS.childmodel')),
            ],
        ),
    ]
