# Generated by Django 5.1 on 2024-09-03 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LCHIS', '0006_alter_guardianmodel_children'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.TextField(null=True)),
                ('type', models.CharField(choices=[('Health Center', 'Health Center'), ('Barangay Hall', 'Barangay Hall'), ('School', 'School'), ('Basketball Court', 'Basketball Court'), ('Church', 'Church'), ('Other', 'Other')], max_length=200, null=True)),
                ('description', models.TextField(null=True)),
                ('date', models.TextField(null=True)),
            ],
        ),
    ]
