# Generated by Django 5.1 on 2024-09-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LCHIS', '0007_gallerymodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerymodel',
            name='image_path',
        ),
        migrations.AddField(
            model_name='gallerymodel',
            name='image',
            field=models.ImageField(null=True, upload_to='gallery/'),
        ),
    ]
