# Generated by Django 5.1 on 2024-09-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LCHIS', '0008_remove_gallerymodel_image_path_gallerymodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerymodel',
            name='date',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gallerymodel',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
