# Generated by Django 5.1 on 2024-09-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LCHIS', '0011_remove_gallerymodel_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childmodel',
            name='image_path',
        ),
        migrations.AddField(
            model_name='childmodel',
            name='barangay',
            field=models.CharField(default='Laguile', max_length=200),
        ),
        migrations.AddField(
            model_name='childmodel',
            name='bcg',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='childmodel',
            name='birthdate',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='childmodel',
            name='hepa_b',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='childmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='child/'),
        ),
        migrations.AddField(
            model_name='childmodel',
            name='ipv_1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='childmodel',
            name='ipv_2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='childmodel',
            name='mcv_1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='childmodel',
            name='mcv_2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='childmodel',
            name='name_of_bhw',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='childmodel',
            name='nurse',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='childmodel',
            name='opv_1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='childmodel',
            name='opv_2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='childmodel',
            name='opv_3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='childmodel',
            name='pcv_1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='childmodel',
            name='pcv_2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='childmodel',
            name='pcv_3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='childmodel',
            name='penta_1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='childmodel',
            name='penta_2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='childmodel',
            name='penta_3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='childmodel',
            name='purok',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
