# Generated by Django 5.1 on 2024-09-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LCHIS', '0012_remove_childmodel_image_path_childmodel_barangay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childmodel',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
