# Generated by Django 5.1 on 2024-09-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LCHIS', '0014_childmodel_remarks_alter_childmodel_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childmodel',
            name='bcg',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='childmodel',
            name='hepa_b',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='childmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='child/'),
        ),
        migrations.AlterField(
            model_name='childmodel',
            name='ipv_1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='childmodel',
            name='ipv_2',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='childmodel',
            name='mcv_1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='childmodel',
            name='mcv_2',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='childmodel',
            name='months_old',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='childmodel',
            name='opv_1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='childmodel',
            name='opv_2',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='childmodel',
            name='opv_3',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='childmodel',
            name='pcv_1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='childmodel',
            name='pcv_2',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='childmodel',
            name='pcv_3',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='childmodel',
            name='penta_1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='childmodel',
            name='penta_2',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='childmodel',
            name='penta_3',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='childmodel',
            name='remarks',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='childmodel',
            name='years_old',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
