# Generated by Django 5.1 on 2024-09-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LCHIS', '0015_alter_childmodel_bcg_alter_childmodel_hepa_b_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardianmodel',
            name='password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='guardianmodel',
            name='username',
            field=models.CharField(max_length=200),
        ),
    ]
