# Generated by Django 5.1 on 2024-09-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LCHIS', '0017_alter_childmodel_bcg_alter_childmodel_hepa_b_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardianmodel',
            name='children',
            field=models.ManyToManyField(blank=True, null=True, to='LCHIS.childmodel'),
        ),
    ]
