# Generated by Django 5.1 on 2024-09-29 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LCHIS', '0018_alter_guardianmodel_children'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardianmodel',
            name='children',
        ),
        migrations.AddField(
            model_name='guardianmodel',
            name='children',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='LCHIS.childmodel'),
            preserve_default=False,
        ),
    ]
