# Generated by Django 5.1 on 2024-09-29 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LCHIS', '0019_remove_guardianmodel_children_guardianmodel_children'),
    ]

    operations = [
        migrations.AddField(
            model_name='childmodel',
            name='condition',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='childmodel',
            name='father_history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='childmodel',
            name='height',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='childmodel',
            name='mother_history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='childmodel',
            name='name_of_father',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='childmodel',
            name='name_of_mother',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='childmodel',
            name='weight',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
