# Generated by Django 5.1 on 2024-09-29 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LCHIS', '0020_childmodel_condition_childmodel_father_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childmodel',
            name='condition',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='childmodel',
            name='height',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='childmodel',
            name='weight',
            field=models.CharField(max_length=200),
        ),
    ]
