# Generated by Django 5.1 on 2024-09-29 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LCHIS', '0021_alter_childmodel_condition_alter_childmodel_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childmodel',
            name='condition',
            field=models.TextField(),
        ),
    ]
