# Generated by Django 5.1 on 2024-09-29 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LCHIS', '0023_alter_guardianmodel_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guardianmodel',
            old_name='children',
            new_name='child',
        ),
    ]
