# Generated by Django 5.1 on 2024-09-29 07:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LCHIS', '0026_alter_guardianmodel_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardianmodel',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
    ]
