# Generated by Django 5.1 on 2024-09-29 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LCHIS', '0027_alter_guardianmodel_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardianmodel',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LCHIS.childmodel'),
        ),
    ]
