# Generated by Django 5.1 on 2024-09-29 07:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LCHIS', '0029_alter_guardianmodel_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardianmodel',
            name='date_joined',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
