# Generated by Django 5.1 on 2024-09-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LCHIS', '0030_alter_guardianmodel_date_joined'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guardianmodel',
            old_name='middle_name',
            new_name='guardian_first_name',
        ),
        migrations.AddField(
            model_name='guardianmodel',
            name='guardian_last_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guardianmodel',
            name='guardian_middle_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guardianmodel',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='guardianmodel',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
