# Generated by Django 5.1 on 2024-09-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LCHIS', '0031_rename_middle_name_guardianmodel_guardian_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guardianmodel',
            old_name='guardian_first_name',
            new_name='middle_name',
        ),
        migrations.RemoveField(
            model_name='guardianmodel',
            name='guardian_last_name',
        ),
        migrations.RemoveField(
            model_name='guardianmodel',
            name='guardian_middle_name',
        ),
        migrations.AlterField(
            model_name='guardianmodel',
            name='first_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='guardianmodel',
            name='last_name',
            field=models.CharField(max_length=200),
        ),
    ]
