# Generated by Django 5.1 on 2024-09-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LCHIS', '0032_rename_guardian_first_name_guardianmodel_middle_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childmodel',
            name='first_name',
            field=models.CharField(max_length=200, verbose_name='child_first_name'),
        ),
    ]
