# Generated by Django 5.1 on 2024-09-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LCHIS', '0033_alter_childmodel_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childmodel',
            name='first_name',
            field=models.CharField(max_length=200),
        ),
    ]
