# Generated by Django 5.1 on 2024-09-29 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LCHIS', '0034_alter_childmodel_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='childmodel',
            old_name='first_name',
            new_name='child_first_name',
        ),
        migrations.RenameField(
            model_name='childmodel',
            old_name='last_name',
            new_name='child_last_name',
        ),
        migrations.RenameField(
            model_name='childmodel',
            old_name='middle_name',
            new_name='child_middle_name',
        ),
    ]
