# Generated by Django 5.1 on 2024-09-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LCHIS', '0035_rename_first_name_childmodel_child_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardianmodel',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
