# Generated by Django 5.1 on 2024-09-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LCHIS', '0039_alter_guardianmodel_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardianmodel',
            name='middle_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
