# Generated by Django 5.1 on 2024-09-29 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LCHIS', '0040_guardianmodel_middle_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='guardianmodel',
            managers=[
            ],
        ),
    ]
