# Generated by Django 5.1 on 2024-10-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LCHIS', '0042_alter_gallerymodel_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='VitaminModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='vitamins/')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
