# Generated by Django 5.1 on 2024-10-05 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LCHIS', '0044_aboutusmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutusmodel',
            old_name='is_main',
            new_name='on_left',
        ),
    ]
