# Generated by Django 5.1 on 2024-11-07 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LCHIS', '0045_rename_is_main_aboutusmodel_on_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitaminmodel',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
