# Generated by Django 5.1 on 2024-11-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LCHIS', '0046_vitaminmodel_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('address', 'Address'), ('contact_number', 'Contact Number'), ('email', 'Email')], default='address', max_length=200)),
                ('header', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
