# Generated by Django 5.1 on 2024-11-07 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LCHIS', '0047_contactusmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactusmodel',
            old_name='type',
            new_name='contact_type',
        ),
    ]
