# Generated by Django 5.1 on 2024-12-06 03:30

import LCHIS.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LCHIS', '0048_rename_type_contactusmodel_contact_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='childmodel',
            name='father_first_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='childmodel',
            name='father_last_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='childmodel',
            name='father_middle_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='childmodel',
            name='mother_first_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='childmodel',
            name='mother_last_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='childmodel',
            name='mother_middle_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='childmodel',
            name='bcg',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[LCHIS.validators.validate_today_date]),
        ),
        migrations.AlterField(
            model_name='childmodel',
            name='hepa_b',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[LCHIS.validators.validate_today_date]),
        ),
        migrations.AlterField(
            model_name='childmodel',
            name='ipv_1',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[LCHIS.validators.validate_today_date]),
        ),
        migrations.AlterField(
            model_name='childmodel',
            name='ipv_2',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[LCHIS.validators.validate_today_date]),
        ),
        migrations.AlterField(
            model_name='childmodel',
            name='mcv_1',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[LCHIS.validators.validate_today_date]),
        ),
        migrations.AlterField(
            model_name='childmodel',
            name='mcv_2',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[LCHIS.validators.validate_today_date]),
        ),
        migrations.AlterField(
            model_name='childmodel',
            name='opv_1',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[LCHIS.validators.validate_today_date]),
        ),
        migrations.AlterField(
            model_name='childmodel',
            name='opv_2',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[LCHIS.validators.validate_today_date]),
        ),
        migrations.AlterField(
            model_name='childmodel',
            name='opv_3',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[LCHIS.validators.validate_today_date]),
        ),
        migrations.AlterField(
            model_name='childmodel',
            name='pcv_1',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[LCHIS.validators.validate_today_date]),
        ),
        migrations.AlterField(
            model_name='childmodel',
            name='pcv_2',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[LCHIS.validators.validate_today_date]),
        ),
        migrations.AlterField(
            model_name='childmodel',
            name='pcv_3',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[LCHIS.validators.validate_today_date]),
        ),
        migrations.AlterField(
            model_name='childmodel',
            name='penta_1',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[LCHIS.validators.validate_today_date]),
        ),
        migrations.AlterField(
            model_name='childmodel',
            name='penta_2',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[LCHIS.validators.validate_today_date]),
        ),
        migrations.AlterField(
            model_name='childmodel',
            name='penta_3',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[LCHIS.validators.validate_today_date]),
        ),
    ]
